name: Deploy GitHub Pages

on:
    push:
        branches: [ master ]

jobs:
    deploy:
        runs-on: ubuntu-latest

        steps:
        - uses: actions/checkout@v2
        -
            name: Set up Python
            uses: actions/setup-python@v2
            with:
                python-version: '3.x'
        -
            uses: actions/setup-node@v2
            with:
                node-version: '14'
        -
            name: Install pipenv
            run: |
                python -m pip install --upgrade pip
                pip install pipenv
        -
            name: Upgrade npm
            run: |
                npm install -g npm@7
        -
            name: Pipenv Cache
            uses: actions/cache@v1
            env:
                cache-name: cache-pipenv
            with:
                path: ~/.local/share/virtualenvs
                key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/Pipfile.lock') }}
                restore-keys: |
                    ${{ runner.os }}-build-${{ env.cache-name }}-
                    ${{ runner.os }}-build-
                    ${{ runner.os }}-
        -
            name: NPM Cache
            uses: actions/cache@v1
            env:
                cache-name: cache-pipenv
            with:
                path: node_modules
                key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
                restore-keys: |
                    ${{ runner.os }}-build-${{ env.cache-name }}-
                    ${{ runner.os }}-build-
                    ${{ runner.os }}-
        -
            name: Install dependencies
            run: |
                pipenv install
                npm ci
        -
            name: Make publish
            run: |
                cp -r doc/public public
        -
            name: Build spec docs
            run: |
                pipenv run make -C doc/spec html
                mv doc/spec/build/html public/spec
        -
            name: Deploy
            uses: peaceiris/actions-gh-pages@v3
            with:
                github_token: ${{ secrets.GITHUB_TOKEN }}
                publish_dir: ./public
                publish_branch: gh-pages
